{
 "title": "Nokia SR OS Topology Dashboard",
 "tags": [
  "Nokia",
  "SR-OS",
  "gNMI"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "router", "label": "Router", "query": { "query": "label_values(source)" } }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage %",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gnmic_sros_cpu_cpu_usage{source=\"$router\"}"
    }
   ]
  },
  {
   "title": "Memory Usage %",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(gnmic_sros_mem_in_use{source=\"$router\"}/gnmic_sros_mem_max_allowed{source=\"$router\"})"
    }
   ]
  },
  {
   "title": "Interfaces UP",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(gnmic_sros_if_oper_state_oper_state{source=\"$router\"})"
    }
   ]
  },
  {
   "title": "BGP Peers UP",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gnmic_sros_bgp_up_peers_up_peers{source=\"$router\"}"
    }
   ]
  },
  {
   "title": "Total RX Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum(rate(gnmic_sros_if_stats_in_octets{source=\"$router\"}[5m]))*8",
     "legendFormat": "RX"
    }
   ]
  },
  {
   "title": "Total TX Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "sum(rate(gnmic_sros_if_stats_out_octets{source=\"$router\"}[5m])) * 8",
     "legendFormat": "TX"
    }
   ]
  },
  {
   "title": "Top 10 RX Interfaces",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "topk(10, rate(gnmic_sros_if_stats_in_octets{source=\"$router\"}[5m])*8)",
     "legendFormat": "{{interface_name}}"
    }
   ]
  },
  {
   "title": "Top 10 TX Interfaces",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "topk(10, rate(gnmic_sros_if_stats_out_octets{source=\"$router\"}[5m])*8)",
     "legendFormat": "{{interface_name}}"
    }
   ]
  },
  {
   "title": "IPv4 Routes",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(gnmic_sros_ipv4_routes_age{source=\"$router\",router_router_name=\"Base\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "IPv6 Routes",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(gnmic_sros_ipv6_routes_age{source=\"$router\",router_router_name=\"Base\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "BGP Active Routes",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gnmic_sros_bgp_routes_stats_active_routes{source=\"$router\", router_router_name=\"Base\"}",
     "legendFormat": "Active Routers"
    }
   ]
  },
  {
   "title": "BGP Paths",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gnmic_sros_bgp_stats_bgp_paths{source=\"$router\"}"
    }
   ]
  }
 ]
}